### ISSUE TITLE
Support optional meta file that describes boilerplates

### ISSUE THREAD

**Issue by alajmo** [samiralajmovic/template-generator#6]
Yaml file:

.boilerplate-generator.yaml
```yaml
---
- boilerplates:
      - name: README
        dest: README.md

      - name: package
        dest: package.json
```
